version: "1"
projects:
  - name: Gello
    environments:
      - name: Production
        services:
          - type: web
            name: Gello
            runtime: node
            repo: https://github.com/gello-co/Gello
            plan: free
            region: ohio
            buildCommand: bun install --frozen-lockfile && bun run build
            startCommand: bun run start
            domains:
              - www.gello.co
              - gello.co
            autoDeployTrigger: commit
            rootDir: .
            previews:
              generation: manual
