version: "1"
projects:
  - name: Gello
    environments:
      - name: Production
        services:
          - type: web
            name: Gello
            runtime: node
            repo: https://github.com/gello-co/Gello
            plan: free
            region: ohio
            buildCommand: bun install && bun run build
            startCommand: doppler run -- bun run start:prd
            healthCheckPath: /api/health
            envVars:
              - key: NODE_ENV
                value: production
              - key: DOPPLER_TOKEN
                sync: false
            domains:
              - www.gello.co
              - gello.co
            autoDeployTrigger: off
            rootDir: .
            previews:
              generation: manual
